[package]
name = "wasm"
version.workspace = true
edition.workspace = true

[dependencies]
app = { path = "../app" }

[build-dependencies]
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-client-gen.workspace = true
sails-idl-gen.workspace = true
app = { path = "../app" }